### ISSUE TITLE
1.7.10 Version Bug

### ISSUE THREAD

**Issue by AlvinIsBack** [frash23/smashhit#2]
When I try to punch something, or someone I get this error.
[code][08:46:30 ERROR]: [AsyncHitDetection] Unhandled exception occured in onAsyncPacket() for AsyncHitDetection
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R4.entity.CraftIronGolem cannot be cast to org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer
        at com.frash23.smashhit.damageresolver.DamageResolver_1_7_R4.getDamage(DamageResolver_1_7_R4.java:25) ~[SmashHit.jar:?]
        at com.frash23.smashhit.SmashHitListener.onPacketReceiving(SmashHitListener.java:98) ~[SmashHit.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:643) [ProtocolLib%20(1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:597) [ProtocolLib%20(1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:49) [ProtocolLib%20(1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [ProtocolLib%20(1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [ProtocolLib%20(1).jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [PaperSpigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [PaperSpigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101] [/code]

**Comment by Vrnt** [comment]
Can you fix this..

**Comment by wuksg** [comment]
I have the same problem.

**Comment by ghost** [comment]
I have resolved the problem on my fork of this repository, also I added 1.11 support
Repository: [https://github.com/Speentie8081/SmashHit](https://github.com/Speentie8081/SmashHit)
By the way, the jar file for the plugin is included in the root of the repository, no compilation needed.
